coverage:
  precision: 2
  round: down
  range: "1...100"
  status:
    patch:
      default:
        target: 60%
    project:
      default:
        target: auto
        threshold: 0.1%
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
    # after_n_builds should match the number of CI jobs configured to upload reports to Codecov
    # in WaterTAP there are 4 such jobs:
    # (1 MPI Workflow + 1 Standard Workflow) * (1 Windows + 1 Linux for a single sample Python version)
    after_n_builds: 4
